# Using the HDF 5 data

#### 1. Reading the file

To open and read data we use the File method in read mode, r.

https://atztogo.github.io/phono3py/hdf5_howto.html

http://docs.h5py.org/en/stable/high/attr.html#AttributeManager.__iter__

In [164]:
import h5py
import pandas as pandas
import numpy as np

file_name = 'LinearElastic/geom_tensionX.hdf5'
hf = h5py.File(file_name,'r')


KeysView(<HDF5 file "geom_tensionX.hdf5" (mode r)>)

To see what data is in this file, we can call the keys() method on the file object.

In [86]:
hf.keys()

KeysView(<HDF5 file "geom_tensionX.hdf5" (mode r)>)

To read data in directories and subdirectories use the get method with the full subdirectory path.

In [201]:
 import re
cell_0 = hf.get('/geometry/cell_0')                        # material point coordinates (Undeformed)
connectivity_cell = hf.get('/geometry/connectivity_cell')  # connectivity for cells
connectivity_elem = hf.get('/geometry/connectivity_elem')  # connectivity for elements
node_0 = hf.get('/geometry/node_0')                        # Nodes defining the vertices of elements and cells (undeformed)
F_inc10 = hf.get('/inc00010/constituent/01_def and firstPicola/F')  
P_inc10 = hf.get('/inc00010/constituent/01_def and firstPicola/P')



In [207]:
list(hf)

['geometry',
 'inc00000',
 'inc00001',
 'inc00002',
 'inc00003',
 'inc00004',
 'inc00005',
 'inc00006',
 'inc00007',
 'inc00008',
 'inc00009',
 'inc00010',
 'mapping']

In [212]:
list(f['geometry'])

['cell_0', 'connectivity_cell', 'connectivity_elem', 'node_0']

In [221]:
np.array(f['geometry']['cell_0'])                    

array([[0.125, 0.125, 0.5  ],
       [0.375, 0.125, 0.5  ],
       [0.625, 0.125, 0.5  ],
       [0.875, 0.125, 0.5  ],
       [0.125, 0.375, 0.5  ],
       [0.375, 0.375, 0.5  ],
       [0.625, 0.375, 0.5  ],
       [0.875, 0.375, 0.5  ],
       [0.125, 0.625, 0.5  ],
       [0.375, 0.625, 0.5  ],
       [0.625, 0.625, 0.5  ],
       [0.875, 0.625, 0.5  ],
       [0.125, 0.875, 0.5  ],
       [0.375, 0.875, 0.5  ],
       [0.625, 0.875, 0.5  ],
       [0.875, 0.875, 0.5  ]])

In [220]:
np.array((f['geometry']['connectivity_cell']))

array([[ 1,  2,  7,  6, 26, 27, 32, 31],
       [ 2,  3,  8,  7, 27, 28, 33, 32],
       [ 3,  4,  9,  8, 28, 29, 34, 33],
       [ 4,  5, 10,  9, 29, 30, 35, 34],
       [ 6,  7, 12, 11, 31, 32, 37, 36],
       [ 7,  8, 13, 12, 32, 33, 38, 37],
       [ 8,  9, 14, 13, 33, 34, 39, 38],
       [ 9, 10, 15, 14, 34, 35, 40, 39],
       [11, 12, 17, 16, 36, 37, 42, 41],
       [12, 13, 18, 17, 37, 38, 43, 42],
       [13, 14, 19, 18, 38, 39, 44, 43],
       [14, 15, 20, 19, 39, 40, 45, 44],
       [16, 17, 22, 21, 41, 42, 47, 46],
       [17, 18, 23, 22, 42, 43, 48, 47],
       [18, 19, 24, 23, 43, 44, 49, 48],
       [19, 20, 25, 24, 44, 45, 50, 49]])

In [223]:
np.array((f['geometry']['connectivity_elem']))

array([[ 1,  2,  7,  6, 26, 27, 32, 31],
       [ 2,  3,  8,  7, 27, 28, 33, 32],
       [ 3,  4,  9,  8, 28, 29, 34, 33],
       [ 4,  5, 10,  9, 29, 30, 35, 34],
       [ 6,  7, 12, 11, 31, 32, 37, 36],
       [ 7,  8, 13, 12, 32, 33, 38, 37],
       [ 8,  9, 14, 13, 33, 34, 39, 38],
       [ 9, 10, 15, 14, 34, 35, 40, 39],
       [11, 12, 17, 16, 36, 37, 42, 41],
       [12, 13, 18, 17, 37, 38, 43, 42],
       [13, 14, 19, 18, 38, 39, 44, 43],
       [14, 15, 20, 19, 39, 40, 45, 44],
       [16, 17, 22, 21, 41, 42, 47, 46],
       [17, 18, 23, 22, 42, 43, 48, 47],
       [18, 19, 24, 23, 43, 44, 49, 48],
       [19, 20, 25, 24, 44, 45, 50, 49]])

In [229]:
list(hf.values())

[<HDF5 group "/geometry" (4 members)>,
 <HDF5 group "/inc00000" (2 members)>,
 <HDF5 group "/inc00001" (2 members)>,
 <HDF5 group "/inc00002" (2 members)>,
 <HDF5 group "/inc00003" (2 members)>,
 <HDF5 group "/inc00004" (2 members)>,
 <HDF5 group "/inc00005" (2 members)>,
 <HDF5 group "/inc00006" (2 members)>,
 <HDF5 group "/inc00007" (2 members)>,
 <HDF5 group "/inc00008" (2 members)>,
 <HDF5 group "/inc00009" (2 members)>,
 <HDF5 group "/inc00010" (2 members)>,
 <HDF5 group "/mapping" (2 members)>]

In [228]:
list(hf.items())

[('geometry', <HDF5 group "/geometry" (4 members)>),
 ('inc00000', <HDF5 group "/inc00000" (2 members)>),
 ('inc00001', <HDF5 group "/inc00001" (2 members)>),
 ('inc00002', <HDF5 group "/inc00002" (2 members)>),
 ('inc00003', <HDF5 group "/inc00003" (2 members)>),
 ('inc00004', <HDF5 group "/inc00004" (2 members)>),
 ('inc00005', <HDF5 group "/inc00005" (2 members)>),
 ('inc00006', <HDF5 group "/inc00006" (2 members)>),
 ('inc00007', <HDF5 group "/inc00007" (2 members)>),
 ('inc00008', <HDF5 group "/inc00008" (2 members)>),
 ('inc00009', <HDF5 group "/inc00009" (2 members)>),
 ('inc00010', <HDF5 group "/inc00010" (2 members)>),
 ('mapping', <HDF5 group "/mapping" (2 members)>)]

In [245]:
f.visit(print)

geometry
geometry/cell_0
geometry/connectivity_cell
geometry/connectivity_elem
geometry/node_0
inc00000
inc00000/constituent
inc00000/constituent/01_def and firstPicola
inc00000/constituent/01_def and firstPicola/F
inc00000/constituent/01_def and firstPicola/P
inc00000/constitutive
inc00000/constitutive/01_Martensite
inc00000/constitutive/01_Martensite/plastic
inc00000/constitutive/02_ferrite
inc00000/constitutive/02_ferrite/plastic
inc00001
inc00001/constituent
inc00001/constituent/01_def and firstPicola
inc00001/constituent/01_def and firstPicola/F
inc00001/constituent/01_def and firstPicola/P
inc00001/constitutive
inc00001/constitutive/01_Martensite
inc00001/constitutive/01_Martensite/plastic
inc00001/constitutive/02_ferrite
inc00001/constitutive/02_ferrite/plastic
inc00002
inc00002/constituent
inc00002/constituent/01_def and firstPicola
inc00002/constituent/01_def and firstPicola/F
inc00002/constituent/01_def and firstPicola/P
inc00002/constitutive
inc00002/constitutive/01_Martensi

'geometry'

'geometry/cell_0'

'geometry/connectivity_cell'

'geometry/connectivity_elem'

'geometry/node_0'

'inc00000'

'inc00000/constituent'

'inc00000/constituent/01_def and firstPicola'

'inc00000/constituent/01_def and firstPicola/F'

'inc00000/constituent/01_def and firstPicola/P'

'inc00000/constitutive'

'inc00000/constitutive/01_Martensite'

'inc00000/constitutive/01_Martensite/plastic'

'inc00000/constitutive/02_ferrite'

'inc00000/constitutive/02_ferrite/plastic'

'inc00001'

'inc00001/constituent'

'inc00001/constituent/01_def and firstPicola'

'inc00001/constituent/01_def and firstPicola/F'

'inc00001/constituent/01_def and firstPicola/P'

'inc00001/constitutive'

'inc00001/constitutive/01_Martensite'

'inc00001/constitutive/01_Martensite/plastic'

'inc00001/constitutive/02_ferrite'

'inc00001/constitutive/02_ferrite/plastic'

'inc00002'

'inc00002/constituent'

'inc00002/constituent/01_def and firstPicola'

'inc00002/constituent/01_def and firstPicola/F'

'inc00002/constituent/01_def and firstPicola/P'

'inc00002/constitutive'

'inc00002/constitutive/01_Martensite'

'inc00002/constitutive/01_Martensite/plastic'

'inc00002/constitutive/02_ferrite'

'inc00002/constitutive/02_ferrite/plastic'

'inc00003'

'inc00003/constituent'

'inc00003/constituent/01_def and firstPicola'

'inc00003/constituent/01_def and firstPicola/F'

'inc00003/constituent/01_def and firstPicola/P'

'inc00003/constitutive'

'inc00003/constitutive/01_Martensite'

'inc00003/constitutive/01_Martensite/plastic'

'inc00003/constitutive/02_ferrite'

'inc00003/constitutive/02_ferrite/plastic'

'inc00004'

'inc00004/constituent'

'inc00004/constituent/01_def and firstPicola'

'inc00004/constituent/01_def and firstPicola/F'

'inc00004/constituent/01_def and firstPicola/P'

'inc00004/constitutive'

'inc00004/constitutive/01_Martensite'

'inc00004/constitutive/01_Martensite/plastic'

'inc00004/constitutive/02_ferrite'

'inc00004/constitutive/02_ferrite/plastic'

'inc00005'

'inc00005/constituent'

'inc00005/constituent/01_def and firstPicola'

'inc00005/constituent/01_def and firstPicola/F'

'inc00005/constituent/01_def and firstPicola/P'

'inc00005/constitutive'

'inc00005/constitutive/01_Martensite'

'inc00005/constitutive/01_Martensite/plastic'

'inc00005/constitutive/02_ferrite'

'inc00005/constitutive/02_ferrite/plastic'

'inc00006'

'inc00006/constituent'

'inc00006/constituent/01_def and firstPicola'

'inc00006/constituent/01_def and firstPicola/F'

'inc00006/constituent/01_def and firstPicola/P'

'inc00006/constitutive'

'inc00006/constitutive/01_Martensite'

'inc00006/constitutive/01_Martensite/plastic'

'inc00006/constitutive/02_ferrite'

'inc00006/constitutive/02_ferrite/plastic'

'inc00007'

'inc00007/constituent'

'inc00007/constituent/01_def and firstPicola'

'inc00007/constituent/01_def and firstPicola/F'

'inc00007/constituent/01_def and firstPicola/P'

'inc00007/constitutive'

'inc00007/constitutive/01_Martensite'

'inc00007/constitutive/01_Martensite/plastic'

'inc00007/constitutive/02_ferrite'

'inc00007/constitutive/02_ferrite/plastic'

'inc00008'

'inc00008/constituent'

'inc00008/constituent/01_def and firstPicola'

'inc00008/constituent/01_def and firstPicola/F'

'inc00008/constituent/01_def and firstPicola/P'

'inc00008/constitutive'

'inc00008/constitutive/01_Martensite'

'inc00008/constitutive/01_Martensite/plastic'

'inc00008/constitutive/02_ferrite'

'inc00008/constitutive/02_ferrite/plastic'

'inc00009'

'inc00009/constituent'

'inc00009/constituent/01_def and firstPicola'

'inc00009/constituent/01_def and firstPicola/F'

'inc00009/constituent/01_def and firstPicola/P'

'inc00009/constitutive'

'inc00009/constitutive/01_Martensite'

'inc00009/constitutive/01_Martensite/plastic'

'inc00009/constitutive/02_ferrite'

'inc00009/constitutive/02_ferrite/plastic'

'inc00010'

'inc00010/constituent'

'inc00010/constituent/01_def and firstPicola'

'inc00010/constituent/01_def and firstPicola/F'

'inc00010/constituent/01_def and firstPicola/P'

'inc00010/constitutive'

'inc00010/constitutive/01_Martensite'

'inc00010/constitutive/01_Martensite/plastic'

'inc00010/constitutive/02_ferrite'

'inc00010/constitutive/02_ferrite/plastic'

'mapping'

'mapping/cellResults'

'mapping/cellResults/constituent'

'mapping/cellResults/constitutive'

'mapping/cells'

In [261]:
np.array(f['geometry']['cell_0'])                 
np.array((f['geometry']['connectivity_elem']))

array([[ 1,  2,  7,  6, 26, 27, 32, 31],
       [ 2,  3,  8,  7, 27, 28, 33, 32],
       [ 3,  4,  9,  8, 28, 29, 34, 33],
       [ 4,  5, 10,  9, 29, 30, 35, 34],
       [ 6,  7, 12, 11, 31, 32, 37, 36],
       [ 7,  8, 13, 12, 32, 33, 38, 37],
       [ 8,  9, 14, 13, 33, 34, 39, 38],
       [ 9, 10, 15, 14, 34, 35, 40, 39],
       [11, 12, 17, 16, 36, 37, 42, 41],
       [12, 13, 18, 17, 37, 38, 43, 42],
       [13, 14, 19, 18, 38, 39, 44, 43],
       [14, 15, 20, 19, 39, 40, 45, 44],
       [16, 17, 22, 21, 41, 42, 47, 46],
       [17, 18, 23, 22, 42, 43, 48, 47],
       [18, 19, 24, 23, 43, 44, 49, 48],
       [19, 20, 25, 24, 44, 45, 50, 49]])

In [272]:
cell_0 = hf.get('/geometry/cell_0')     